export const environment = {
  production: false,
  apiBaseUrl: '/api',
  gatewayUrl: 'http://localhost:8080',
  employeeApiUrl: '/api/v1/employees',
  payrollApiUrl: '/api/payrolls',
  notificationApiUrl: '/api/v1/notifications',
  authApiUrl: '/api/auth',
  searchApiUrl: '/api/search',
  sagaApiUrl: '/api/sagas',
  metricsApiUrl: '/api/metrics',
  filesApiUrl: '/api/v1/files',
  graphqlUrl: '/graphql',
  wsEndpoint: 'ws://localhost:8080/ws',
};
