package com.example.notification.repository;

import com.example.notification.dto.NotificationFilter;
import com.example.notification.model.Notification;
import com.example.notification.model.Notification_;
import org.springframework.data.jpa.domain.Specification;

import java.time.LocalDateTime;

/**
 * JPA Specification Builder — Dynamic, type-safe query construction.
 *
 * Interview Insight:
 *   "How do you handle complex search/filter queries without writing N methods?"
 *   → "Use Spring Data JPA Specifications. Each filter criterion is a separate
 *      Specification<T> that builds a JPA Criteria predicate. They compose
 *      via .and() and .or() — like building blocks for WHERE clauses.
 *
 *      Benefits:
 *        1. No query explosion — 7 filters × 2 (on/off) = 128 combinations,
 *           but we write only 7 Specification methods
 *        2. Type-safe with JPA Metamodel (Notification_ generated class)
 *        3. Composable: Spec.where(a).and(b).or(c)
 *        4. Reusable across different query endpoints
 *        5. Null-safe — null criteria are simply skipped
 *
 *      Spring Data usage:
 *        repository.findAll(
 *            NotificationSpecification.buildFrom(filter),
 *            pageable
 *        )"
 *
 *   "What is the JPA Metamodel (Notification_)?"
 *   → "A compile-time generated class with static fields for each entity
 *      attribute. Provides type-safe column references instead of strings.
 *      Generated by Hibernate's annotation processor."
 *
 * NOTE: If the JPA Metamodel (Notification_) is not generated, string-based
 * column names are used as fallback. To generate it, add hibernate-jpamodelgen.
 */
public final class NotificationSpecification {

    private NotificationSpecification() {} // Utility class

    /**
     * Build a composite Specification from a filter DTO.
     * Each non-null field adds a WHERE clause.
     */
    public static Specification<Notification> buildFrom(NotificationFilter filter) {
        return Specification
                .where(hasRecipientId(filter.recipientId()))
                .and(hasChannelType(filter.channelType()))
                .and(hasStatus(filter.status()))
                .and(hasPriority(filter.priority()))
                .and(createdAfter(filter.fromDate()))
                .and(createdBefore(filter.toDate()))
                .and(containsSearchTerm(filter.searchTerm()));
    }

    /**
     * Filter by recipient ID.
     */
    public static Specification<Notification> hasRecipientId(String recipientId) {
        return (root, query, cb) -> {
            if (recipientId == null || recipientId.isBlank()) return null;
            return cb.equal(root.get("recipientId"), recipientId);
        };
    }

    /**
     * Filter by channel type.
     */
    public static Specification<Notification> hasChannelType(Notification.ChannelType channelType) {
        return (root, query, cb) -> {
            if (channelType == null) return null;
            return cb.equal(root.get("channelType"), channelType);
        };
    }

    /**
     * Filter by notification status.
     */
    public static Specification<Notification> hasStatus(Notification.NotificationStatus status) {
        return (root, query, cb) -> {
            if (status == null) return null;
            return cb.equal(root.get("status"), status);
        };
    }

    /**
     * Filter by priority level.
     */
    public static Specification<Notification> hasPriority(Notification.Priority priority) {
        return (root, query, cb) -> {
            if (priority == null) return null;
            return cb.equal(root.get("priority"), priority);
        };
    }

    /**
     * Filter: created after a given date.
     */
    public static Specification<Notification> createdAfter(LocalDateTime fromDate) {
        return (root, query, cb) -> {
            if (fromDate == null) return null;
            return cb.greaterThanOrEqualTo(root.get("createdDate"), fromDate);
        };
    }

    /**
     * Filter: created before a given date.
     */
    public static Specification<Notification> createdBefore(LocalDateTime toDate) {
        return (root, query, cb) -> {
            if (toDate == null) return null;
            return cb.lessThanOrEqualTo(root.get("createdDate"), toDate);
        };
    }

    /**
     * Full-text search across title + message using LIKE.
     *
     * Interview: "How would you improve this for production?"
     *   → "Use PostgreSQL full-text search (tsvector/tsquery) or Elasticsearch
     *      for proper tokenization, stemming, and relevance ranking."
     */
    public static Specification<Notification> containsSearchTerm(String searchTerm) {
        return (root, query, cb) -> {
            if (searchTerm == null || searchTerm.isBlank()) return null;
            String pattern = "%" + searchTerm.toLowerCase() + "%";
            return cb.or(
                    cb.like(cb.lower(root.get("title")), pattern),
                    cb.like(cb.lower(root.get("message")), pattern)
            );
        };
    }
}
